### ISSUE TITLE
use data and inst folders properly

### ISSUE THREAD

**Issue by tjmahr** [dmirman-zz/gazer#7]
The excel spreadsheets should go in `inst/extdata`. See http://r-pkgs.had.co.nz/data.html for how to use the data folder.

The current arrangement fails a CRAN package check.

```
* checking contents of 'data' directory ... WARNING
Files not of a type allowed in a 'data' directory:
  'FixData_v1_N15.xls' 'FixData_v2_N15.xls'
```

**Comment by dmirman-zz** [comment]
I've moved them and updated the vignette. Thanks for catching this.
